version: '2.7'

services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    hostname: db
    container_name: PicassoDB

  rabbit:
    image: rabbitmq:latest
    restart: always
    container_name: rabbitmq
    volumes:
      - data:/var/lib/rabbitmq/
      - log:/var/log/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  dajngo:
    build: .
    container_name: django_picasso_api
    volumes:
      - media:/app/picasso_api/media/
    restart: on-failure
    ports:
      - "8000:8000"
    tty: true
    command:
      bash -c "python manage.py migrate file_hosting_api && python manage.py runserver 0.0.0.0:8000"

  worker:
    restart: always
    build:
      context: .
    environment:
      C_FORCE_ROOT: 'true'
    depends_on:
      - rabbit
    command:
      bash -c "celery -A picasso_api worker -l INFO"


volumes:
  dbdata:
  media:
  data:
  log: