# Generated by Django 4.2.5 on 2023-10-02 19:33

from django.db import migrations, models
import file_hosting_api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('file_hosting_api', '0002_alter_filemodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(unique=True, upload_to=file_hosting_api.utils.get_upload_path_depends_on_extension),
        ),
    ]
